### ISSUE TITLE
improve delete button design on ImageFileComponent

### ISSUE THREAD

**Issue by dejan-marlovic** [afpatmin/fo_components#73]
Too much vertical padding
![Annotation 2019-11-06 144538](https://user-images.githubusercontent.com/6923203/68303456-37dba700-00a4-11ea-8768-3fdbabe5414b.png)

**Comment by afpatmin** [comment]
Fixed in https://github.com/afpatmin/fo_components/commit/a76bf7096ff741b6649496d9305920922893a27f
