### ISSUE TITLE
DataTable data change issue

### ISSUE THREAD

**Issue by muarifer** [afpatmin/fo_components#74]
Hello,

When "data" change in DataTable, table didn't refresh itself.
But when i click the "Filter" in top of table, data has changed.

That's because of, table created by "filteredKeys" value. If data has changed, filteredKeys must reload itself too.

**Comment by afpatmin** [comment]
Hey @muarifer 

DataTable uses ChangeDetectionStrategy.OnPush, so changing values inside of "data" will not trigger change detection unfortunately. 

A possible solution could be that you rebuild "data" whenever it changes (as in `data = new Map.from(data)`)

Another solution that I've been using is to set the "disabled" input to true before changing the data, and then setting it back to false afterwards. Please note this would have to be done in an async function for change detection to trigger. something like:
```dart
bool loading;
Map<Object, Object> data = {};

void updateData() async {
   loading = true;
   /// Some await call here
   data[5].name = 'muarifer';
   loading = false;
}
```

**Comment by muarifer** [comment]
Hello,

> A possible solution could be that you rebuild "data" whenever it changes (as in data = new Map.from(data))

I try this (because of ChangeDetectionStrategy.OnPush) but won't work.

> <fo-data-table [data]="data" [disabled]="loading"></fo-data-table>

[disabled] works well.

Thanks.
